# Workflow to test latest climate-aware-task-scheduler release against ephemeral Slurm cluster
name: cluster-tests

on:
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/cluster-tests.yml'
    - 'cluster/**'
    - 'cats/**.py'
    - 'pyproject.toml'
    - '!cluster/README.md'
  pull_request:
    branches: [ main ]
    paths:
    - '.github/workflows/cluster-tests.yml'
    - 'cluster/**'
    - 'cats/**.py'
    - 'pyproject.toml'
    - '!cluster/README.md'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
    - uses: actions/checkout@v4
    - name: Log in to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Start slurm cluster and install CATS
      run: |
        ./cluster/start.sh
        ./cluster/install_cats.sh
    - name: Run tests
      run: |
        sleep 30  # wait for cluster to come up
        ./cluster/tests.sh
