# Workflow to test latest climate-aware-task-scheduler release against ephemeral Slurm cluster
name: cluster-tests

on:
  push:
    branches: [ main ]
    paths:
    - '.github/workflows/cluster-tests.yml'
    - 'cluster/**'
    - '!cluster/README.md'
  pull_request:
    branches: [ main ]
    paths:
    - '.github/workflows/cluster-tests.yml'
    - 'cluster/**'
    - '!cluster/README.md'
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build slurm container
      run: |
        ./cluster/clone.sh
        ./cluster/build.sh
    - name: Run tests
      run: |
        sleep 30  # wait for cluster to come up
        ./cluster/tests.sh
